// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/8841dfc744bce6b2d3e075f7ace25c0c1e664c17/express-domain-middleware/index.d.ts
declare module "express-domain-middleware" {
    import express = require('express');
    function e(req: express.Request, res: express.Response, next: express.NextFunction): any;
    export = e;
}
